services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.28
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elasticity
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: kibana:7.17.28
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elasticity
    ports:
      - "5601:5601"
    networks:
      - elastic

networks:
  elastic:
